name: us2 - Dropper Deploy

on:
  workflow_dispatch:
  pull_request:

jobs:
  build_ubuntu:

    runs-on: ubuntu-latest
    environment: us2

    name: us2 - Dropper Deploy

    permissions:
      id-token: write

    steps:
      - name: Check out code.
        uses: actions/checkout@v4

      - id: dropper_composite
        uses: ./.github/actions/dropper
        with:
          s3_bucket: ${{ secrets.BUCKET_NAME }}
          aws_region: ${{ secrets.BUCKET_REGION }}
          aws_role: ${{ secrets.US2_S3_ACCOUNT_DEPLOYMENT_ROLE }}
          slack_notification: ${{ secrets.US2_SLACK_URL }}
