name: Swift Alpha

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        working-directory: swift/probe
        run: swift build
      - name: Run tests
        run: swift test