name: Prod Deploy (presto)

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build_ubuntu:

    runs-on: ubuntu-latest
    environment: prod

    name: Prod Deploy (presto)

    steps:
      - name: Check out code. 
        uses: actions/checkout@v3
      
      - id: shell_probes_composite
        uses: ./.github/actions/presto
        with:
          environment: prod
          s3_bucket: ${{ secrets.BUCKET_NAME }}
          aws_region: ${{ secrets.BUCKET_REGION }}
          aws_access_key_id: ${{ secrets.PROD_S3_DEPLOYMENT_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.PROD_S3_DEPLOYMENT_SECRET_KEY  }}
          slack_workflow_url: ${{ secrets.SLACK_GIT_DEPLOYMENT_WORKFLOW }}