name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint \
          --disable=missing-module-docstring \
          --disable=use-dict-literal \
          --disable=invalid-name \
          --disable=wrong-import-order \
          --disable=missing-class-docstring \
          --disable=broad-exception-raised \
          --disable=missing-function-docstring \
          --disable=trailing-whitespace \
          --disable=broad-exception-caught \ 
          --disable=import-error \
          --max-line-length=150 \
          $(git ls-files '*.py')
