name: us2 - shell probes (nocturnal / raindrop / vision scripts) deploy

on:
  workflow_dispatch:

jobs:
  build_ubuntu:

    runs-on: ubuntu-latest
    environment: us2

    name: us2 - shell probes (nocturnal / raindrop / vision scripts) deploy

    permissions:
      id-token: write

    steps:
      - name: Check out code.
        uses: actions/checkout@v4

      - name: Env Conversion
        shell: bash
        run: |
          for i in shell/probe/nocturnal.sh shell/probe/raindrop.ps1 shell/probe/vision.sh; do
            echo "Endpoint substitution for ${i}"
            sed -i 's/prelude-account-us1-us-east-2.s3.amazonaws.com/${{ secrets.BUCKET_NAME }}.s3.amazonaws.com/g' ${i}
            sed -i 's!api.preludesecurity.com!api.us2.preludesecurity.com!g' ${i}
          done

      - id: shell_probes_composite
        uses: ./.github/actions/shell_probes
        with:
          s3_bucket: ${{ secrets.BUCKET_NAME }}
          aws_region: ${{ secrets.BUCKET_REGION }}
          aws_role: ${{ secrets.US2_S3_ACCOUNT_DEPLOYMENT_ROLE }}
          slack_notification: ${{ secrets.US2_SLACK_URL }}
