name: us1 - shell probes (demo / nocturnal / raindrop / vision scripts) deploy

on:
  workflow_dispatch:

jobs:
  build_ubuntu:

    runs-on: ubuntu-latest
    environment: us1

    name: us1 - shell probes (demo / nocturnal / raindrop / vision scripts) deploy

    steps:
      - name: Check out code. 
        uses: actions/checkout@v3
      
      - name: Env Conversion
        shell: bash
        run: |
          for i in shell/probe/nocturnal.sh shell/probe/raindrop.ps1 shell/probe/vision.sh; do
            echo "Endpoint substitution for ${i}"
            sed -i 's!api.preludesecurity.com!api.us1.preludesecurity.com!g' ${i}
          done

      - id: shell_probes_composite
        uses: ./.github/actions/shell_probes
        with:
          environment: us1
          s3_bucket: ${{ secrets.BUCKET_NAME }}
          aws_region: ${{ secrets.BUCKET_REGION }}
          aws_access_key_id: ${{ secrets.US1_S3_DEPLOYMENT_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.US1_S3_DEPLOYMENT_SECRET_ACCESS_KEY  }}
          slack_workflow_url: ${{ secrets.SLACK_GIT_DEPLOYMENT_WORKFLOW }}
