name: us2 - shell probes (demo / nocturnal / raindrop scripts) deploy

on:
  pull_request:
  push:
    branches:
      - master
    paths:
      - 'shell/probe/**'
  workflow_dispatch:    

jobs:
  build_ubuntu:

    runs-on: ubuntu-latest
    environment: us2

    name: us2 - shell probes (demo / nocturnal / raindrop scripts) deploy

    steps:
      - name: Check out code. 
        uses: actions/checkout@v3

      - name: Env Conversion
        shell: bash
        run: |
          for i in shell/probe/nocturnal.sh shell/probe/raindrop.ps1; do
            echo "Staging substitution for ${i}"
            sed -i 's/prelude-account-us1-us-west-1.s3.amazonaws.com/${{ secrets.BUCKET_NAME }}.s3.amazonaws.com/g' ${i}
            sed -i 's!api.preludesecurity.com!api.us2.preludesecurity.com!g' ${i}
          done

      - id: shell_probes_composite
        uses: ./.github/actions/shell_probes
        with:
          environment: us2
          s3_bucket: ${{ secrets.BUCKET_NAME }}
          aws_region: ${{ secrets.BUCKET_REGION }}
          aws_access_key_id: ${{ secrets.US2_S3_DEPLOYMENT_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.US2_S3_DEPLOYMENT_SECRET_ACCESS_KEY  }}
          slack_workflow_url: ${{ secrets.SLACK_GIT_DEPLOYMENT_WORKFLOW }}